name: Daily News Collection

on:
  schedule:
    - cron: '0 7 * * *'  # 7 AM UTC (adjust for your timezone)
  workflow_dispatch:  # Manual trigger option

jobs:
  run-news-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create logs directory
        run: mkdir -p logs
      
      - name: Run News Agent System (Agents SDK)
        run: python github_actions_main.py
        continue-on-error: true
        
      - name: Run News Agent System (Simple Fallback)
        if: failure()
        run: python github_actions_simple.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
      
      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: news-agent-logs-${{ github.run_number }}
          path: logs/
          retention-days: 7